# Generated by Django 4.0.4 on 2023-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
