# Generated by Django 4.0.4 on 2023-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_remove_organization_address_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='Established On:'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Description'),
        ),
    ]
