version: '3.0'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code/
    #      - media_volume:/code/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - ./core/static:/code/core/static
      - ./media:/code/media
    ports:
      - "2023:80"
    depends_on:
      - web

volumes:
  postgres:
#  static_volume:
#  media_volume:
