# Generated by Django 4.0.4 on 2023-01-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_of_Expertise', models.CharField(max_length=10)),
                ('Experience_Years', models.CharField(max_length=10)),
            ],
        ),
    ]
