# Generated by Django 4.0.4 on 2023-02-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expertise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertiseField',
            new_name='Expertise',
        ),
    ]
