# Generated by Django 4.0.4 on 2023-02-07 11:46

import apps.Expertise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expertise', '0002_rename_expertisefield_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='Experience_Years',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='Field_of_Expertise',
        ),
        migrations.AddField(
            model_name='expertise',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='expertise',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='expertise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.Expertise.models.path_and_rename),
        ),
    ]
