# Generated by Django 4.0.4 on 2023-03-16 07:59

import apps.Tool.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.Tool.models.tool_path)),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='user_tool', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
