# Generated by Django 4.0.4 on 2023-03-15 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Team', '0002_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
