# Generated by Django 4.0.4 on 2023-02-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_email', models.CharField(max_length=255, verbose_name='Username/Email')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
