# Generated by Django 4.0.4 on 2023-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username/Email'),
        ),
    ]
