# Generated by Django 4.0.4 on 2023-01-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('name_eng', models.CharField(default='', max_length=200, verbose_name='name_eng')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('name_eng', models.CharField(default='', max_length=200, verbose_name='name_eng')),
                ('locallevel_type', models.CharField(default='', max_length=200, verbose_name='locallevel_type')),
                ('wards', models.IntegerField(blank=True, null=True, verbose_name='wards')),
                ('locallevel_code', models.IntegerField(verbose_name='locallevel_code')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_municipalities', to='NepalAdministrativeDivision.districtdetail')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='ProvincesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('name_eng', models.CharField(default='', max_length=200, verbose_name='name_eng')),
                ('state_number', models.CharField(default='', max_length=20, verbose_name='state_number')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='WardDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_eng', models.CharField(blank=True, max_length=200, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_wards', to='NepalAdministrativeDivision.municipalitydetail')),
            ],
        ),
        migrations.AddField(
            model_name='districtdetail',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_districts', to='NepalAdministrativeDivision.provincesdetail'),
        ),
    ]
