# Generated by Django 4.0.4 on 2023-02-07 09:42

import apps.Project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('project_images', models.ImageField(blank=True, null=True, upload_to=apps.Project.models.path_and_rename)),
                ('project_url', models.CharField(max_length=500, verbose_name='Project Url: ')),
            ],
        ),
    ]
