# Generated by Django 4.0.4 on 2023-02-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skill', '0002_alter_inputskill_skill_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputSkill',
            new_name='Skill',
        ),
    ]
