# Generated by Django 4.0.4 on 2023-02-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Highlights', '0002_alter_highlights_title'),
        ('Organization', '0003_organization_established_date_and_more'),
        ('Experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='highlights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='Highlights.highlights'),
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='Organization.organization'),
        ),
    ]
