# Generated by Django 4.0.4 on 2023-03-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Individual', '0010_remove_individual_experience_and_more'),
        ('Experience', '0002_experience_highlights_experience_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_person', to='Individual.individual'),
        ),
    ]
