# Generated by Django 4.0.4 on 2023-01-23 06:22

import apps.Individual.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.Individual.models.path_and_rename)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('contact', models.TextField(blank=True, max_length=255, null=True, verbose_name='Contact')),
                ('remarks', models.TextField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('religions', models.CharField(choices=[('hindu', 'Hindu'), ('christian', 'Christian'), ('buddhist', 'Buddhist'), ('muslim', 'Muslim')], max_length=255, verbose_name='Religions')),
                ('ethnicity', models.CharField(choices=[('brahmin', 'Brahmin'), ('chhetri', 'Chhetri'), ('baishya', 'Baishya'), ('shudra', 'Shudra')], max_length=255, verbose_name='Ethnicity')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('created_date', models.DateField(auto_now=True, verbose_name='Time of Death')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='Address.address')),
            ],
        ),
    ]
