# Generated by Django 4.0.4 on 2023-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Individual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='First  Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Middle  Name'),
        ),
    ]
