# Generated by Django 4.0.4 on 2023-01-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Individual', '0002_individual_first_name_individual_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='date_of_birth',
        ),
    ]
