# Generated by Django 4.0.4 on 2023-02-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
        ('Individual', '0003_remove_individual_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='Team.team'),
        ),
    ]
