# Generated by Django 4.0.4 on 2023-02-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('Individual', '0004_individual_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.project'),
        ),
    ]
