# Generated by Django 4.0.4 on 2023-02-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProgrammingLanguage', '0001_initial'),
        ('Individual', '0004_individual_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='programming_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='langaugeinfo', to='ProgrammingLanguage.programminglanguage'),
        ),
    ]
