# Generated by Django 4.0.4 on 2023-02-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Experience', '0001_initial'),
        ('Individual', '0005_individual_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience', to='Experience.experience'),
        ),
    ]
