# Generated by Django 4.0.4 on 2023-02-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_organization_established_date_and_more'),
        ('Individual', '0005_individual_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.organization'),
        ),
    ]
