# Generated by Django 4.0.4 on 2023-02-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Individual', '0006_individual_experience'),
        ('Individual', '0006_individual_organization'),
    ]

    operations = [
    ]
