# Generated by Django 4.0.4 on 2023-02-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Expertise', '0003_remove_expertise_experience_years_and_more'),
        ('Individual', '0008_remove_individual_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expertise', to='Expertise.expertise'),
        ),
    ]
