# Generated by Django 4.0.4 on 2023-03-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Individual', '0009_individual_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='programming_language',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='team',
        ),
    ]
